language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
  - sudo apt-get -y install jq
  - rustup component add llvm-tools-preview
  - cargo install cargo-binutils
  - cargo profdata -- --help

script:
  - bash -x scripts/test_coverage.sh
